### PR TITLE
Add composer as new service on docker-compose.yml

### PR DESCRIPTION
**Pull request by leonampd**
This repo offers to developers a docker way to work with magento and pagarme-magento module. But there was a manual process: install composer from a [pagarme-composer](https://hub.docker.com/r/pagarme/composer/) image:

```
docker run -it --rm -v $(pwd):/code -w /code pagarme/composer install
```

This is necessary to magento works well with our module. So, this PR includes an automation for this installation process adding the configurations to `docker-compose.yml`

### CODE REVIEW

**Comment by leonampd** [comment]
@devdrops I don't understand when you say "target image". When I execute `docker run...` I'm running the composer within a container, right? So, adding this service based on `pagarme/composer` image to `docker-compose` and setting the `command` tag I'm creating an abstraction for that command. I mean that, during "up" process, docker will execute the commands defined in the tag `command`: in this case `composer install`.

About your sugestion, I'll send a new commit to change the directories.

Thanks!

**Comment by devdrops** [comment]
> @devdrops I don't understand when you say "target image". When I execute docker run... I'm running the composer within a container, right? So, adding this service based on pagarme/composer image to docker-compose and setting the command tag I'm creating an abstraction for that command. I mean that, during "up" process, docker will execute the commands defined in the tag command: in this case composer install.

In the commit, you wrote the command as

```
docker run -it --rm -v .:/code -w /code install
```

When it should be

```
docker run -it --rm -v .:/code -w /code pagarme/composer install
```

When I said about the target image, I meant that the image name was missing from your example :wink:

**Comment by leonampd** [comment]
Ah! Sorry! My bad.

**Comment by devdrops** [comment]
@leonampd no worries! I suggest to use `git rebase -i` to edit the commit message, in order to keep the right instruction :wink:

**Comment by leonampd** [comment]
@devdrops Done. I think it's ok.

Thanks a lot! =D

**Comment by devdrops** [comment]
@leonampd the commit message hasn't changed :(

**Comment by leonampd** [comment]
> @leonampd the commit message hasn't changed :(

@devdrops Can u check again, pls?

**Comment by devdrops** [comment]
@leonampd AWW YISS

**Comment by lflimeira** [comment]
@leonampd what about this PR?

**Pull request merged**
